apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-db-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: postgres-database
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_URL
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: POSTGRES_URL
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: pg-hba-volume
              mountPath: /etc/postgresql/pg_hba.conf
              subPath: pg_hba.conf
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
        - name: orders-api
          image: vilacaro/api:latest
          ports:
            - containerPort: 9000
          env:
            - name: POSTGRES_URL
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: POSTGRES_URL
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: POSTGRES_PASSWORD
            - name: ASPNETCORE_URLS
              value: "http://0.0.0.0:9000"
          command:
            - "sh"
            - "-c"
            - |
              echo "Iniciando API..." && exec dotnet api.dll
              # Container do PostgreSQL
      volumes:
        - name: postgres-data
          emptyDir: {}
        - name: pg-hba-volume
          configMap:
            name: pg-hba-config