apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  POSTGRES_PASSWORD: cG9zdGdyZXM=  # "postgres" codificado em base64
  DB_PASSWORD: cG9zdGdyZXM=  # "postgres" codificado em base64
  PORTGRES_URL: "SG9zdD1kYi1zZXJ2aWNlO1BvcnQ9NTQzMjtEYXRhYmFzZT1mb29kb3JkZXJkYjtVc2VybmFtZT1wb3N0Z3JlcztQYXNzd29yZD1wb3N0Z3Jlcw=="