apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db-deployment
        image: postgres:latest
        ports:
        - containerPort: 80
        env:
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: my-app-config
                key: DB_NAME
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: my-app-config
                key: DB_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: my-app-secrets
                key: DB_PASSWORD