apiVersion: v1
kind: Secret
metadata:
  name: my-app-secrets
  namespace: default
type: Opaque
data:
  API_KEY: c2VjcmV0X2tleV92YWx1ZQ== # Valor codificado em base64
  DB_PASSWORD: cGFzc3dvcmQ= # Valor codificado em base64
