apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: default
  labels:
    app: db
spec:
  type: NodePort
  selector:
    app: db  # Alinhado com o label do Deployment
  ports:
  - protocol: TCP
    port: 5432         # Porta externa
    targetPort: 5432   # Porta do container
