apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: default
  labels:
    app: db
spec:
  type: LoadBalancer
  selector:
    app: db  # Alinhado com o label do Deployment
  ports:
  - name: postgres
    protocol: TCP 
    port: 5432
    targetPort: 5432
  - name: api
    protocol: TCP 
    port: 9000
    targetPort: 9000